apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: jenkins
spec:
  volumeName: api-jenkins
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
