apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-jenkins
  namespace: jenkins
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/jenkins_home/
