apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: python-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: namhn89/fastapi:{tag}
        env:
          - name: DB_HOST
            value: postgres
          - name: DB_DATABASE
            value: your_database_name
          - name: DB_USERNAME
            value: your_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: DATABASE_URL
            value: postgresql://${DB_DATABASE}:${DB_PASSWORD}@postgres:5432/${DB_DATABASE}
        ports:
        - containerPort: 8000
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: training-python-ingress
#   namespace: python-demo
# spec:
#   ingressClassName: cilium
#   rules:
#   - host: "python.nam.com"
#     http:
#       paths:
#       - backend:
#           service:
#             name: fastapi-app-service
#             port:
#               number: 8000
#         path: /
#         pathType: Prefix
