apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
  namespace: python-demo
spec:
  ports:
    - name: fastapi-app-http
      port: 8000
      targetPort: http
  selector:
    app: fastapi-app
